name: Update Gnome Extension

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-lint:
    runs-on: ubuntu-latest
    name: Run linter
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: "main"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-gnome-extension:
    if: >-
      github.event_name == 'push' || 
      github.event.pull_request.merged == true
    name: Build extension
    needs: run-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
              - '*.js'  
      - name: Build
        if: steps.changes.outputs.src == 'true'
        run: |-
          # shellcheck disable=SC2035
          sed -i 's#^\s\+log#// log#g' *.js 
          # shellcheck disable=SC2035
          zip gnome-extension-${{ github.sha }}.zip icons/ schemas/ metadata.json *.js *.css
      - name: Archive gnome-extension artifact
        if: steps.changes.outputs.src == 'true'
        uses: actions/upload-artifact@v2
        with:
          name: gnome-extension-${{ github.sha }}
          path: gnome-extension-${{ github.sha }}.zip
          
  upload-extension:
    if: >-
      github.event_name == 'push' || 
      github.event.pull_request.merged == true
    name: Upload extension
    runs-on: ubuntu-latest
    needs: build-gnome-extension
    steps:
      - name: Download bundle artifact
        uses: actions/download-artifact@v3
        with:
          name: gnome-extension-${{ github.sha }}

      - name: Install webstore cli
        run: |-
          pip install gnome-extension-uploader
      - name: Upload step
        run: |-
          geu publish --username "${{ secrets.CI_USERNAME }}" --password "${{ secrets.CI_PASSWORD }}"
